version: '3'

services:
    airflow:
        container_name: webserver
        restart: always
        build: .
        privileged: true
        ports: 
            - "8080:8080"
            - "8793:8793"
        volumes: 
            - /var/airflow/logs
        command: webserver
        networks:
            - airflow-network
    mysql:
        container_name: mysql
        restart: always
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        depends_on:
            - postgres       
        environment:
            MYSQL_ROOT_PASSWORD: airflow_root_password
            MYSQL_DATABASE: airflow_metadata_db
            MYSQL_USER: airflow_user
            MYSQL_PASSWORD: airflow_password
        ports:
            - "3306:3306"
        networks:
            - airflow-network



networks:
    airflow-network: