version: '3'

services:
    airflow:
        container_name: webserver
        build: .
        privileged: true
        ports: 
            - "8080:8080"
            - "8793:8793"
        volumes: 
            - /var/airflow/logs
        command: webserver
        networks:
            - airflow-network

networks:
    airflow-network: